### ISSUE TITLE
Internal Server error 500 on promote

### ISSUE THREAD

**Issue by bylshaun** [RedHatSatellite/katello-cvmanager#67]
Satellite Version 6.5.1 

Getting the following error when trying to promote to life cycle environment :

```
root@lsat1p:~/katello-cvmanager# ./cvmanager --config=rhel7_ccv.yaml --wait promote --to-lifecycle-environment 2
Inspecting rhel7_ccv
 Promoting latest version to lifecycle-environment 2
E, [2019-06-24T15:25:07.071573 #55474] ERROR -- : 500 Internal Server Error
Traceback (most recent call last):
        18: from ./cvmanager:545:in `<main>'
        17: from ./cvmanager:347:in `promote'
        16: from ./cvmanager:347:in `each'
        15: from ./cvmanager:359:in `block in promote'
        14: from /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.2/lib/apipie_bindings/resource.rb:21:in `call'
        13: from /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.2/lib/apipie_bindings/api.rb:185:in `call'
        12: from /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.2/lib/apipie_bindings/api.rb:190:in `call_action'
        11: from /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.2/lib/apipie_bindings/api.rb:240:in `http_call'
        10: from /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.2/lib/apipie_bindings/api.rb:327:in `call_client'
         9: from /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/resource.rb:67:in `post'
         8: from /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:52:in `execute'
         7: from /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:145:in `execute'
         6: from /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:715:in `transmit'
         5: from /opt/rh/rh-ruby25/root/usr/share/ruby/net/http.rb:910:in `start'
         4: from /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:725:in `block in transmit'
         3: from /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/request.rb:807:in `process_result'
         2: from /opt/theforeman/tfm/root/usr/share/gems/gems/apipie-bindings-0.2.2/lib/apipie_bindings/api.rb:353:in `block in rest_client_call_block'
         1: from /opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/abstract_response.rb:103:in `return!'
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-2.0.1/lib/restclient/abstract_response.rb:223:in `exception_with_response': 500 Internal Server Error (RestClient::InternalServerError)
```

Use the following yml configuration file : 

```
---
:settings:
  :user: admin
  :pass: redhat123
  :uri: https://lsat1p.fenetwork.com
  :timeout: 300
  :org: 1
  :keep: 5
  :verify_ssl: false
  :lifecycle: 2
:ccv:
  rhel7_ccv:
    rhel7_cv: latest
    fecs7_cv: latest
    epel7_cv: latest
:publish:
  - rhel7_cv
  - fecs7_cv
  - epel7_cv
:promote:
  - rhel7_ccv
```

What do we do to fix this?

**Comment by gearboxscott** [comment]
BTW, for the issue above, the composite views are set to auto-publish so I don't know if that makes a difference or not?

**Comment by gearboxscott** [comment]
We found a solution, which was `auto-publish` was enabled on the composite views which was causing the issue.  so if you promote composite view then turn off auto publish on them.

**Comment by gearboxscott** [comment]
@ bylshaun , you can close this issue by hitting close.
