### ISSUE TITLE
cvmanager not working with Sat 6.5.2?

### ISSUE THREAD

**Issue by jlim0930** [RedHatSatellite/katello-cvmanager#70]
Just upgraded from 6.2 to 6.5 and testing out various cvmanager commands.

using the same yaml file that I used to use on 6.2

```
---
:settings:
  :user: user
  :pass: userpass
  :uri: https://localhost
  :timeout: 300
  :org: 1
  :lifecycle: 58
  :keep: 3
:cv:
  rhel-7-server: latest
:promote:
  - rhel-7-server
:publish:
  - rhel-7-server
```

./cvmanager --config=rhel-7-server.yaml --wait publish
Inspecting rhel-7-server as listed in CSV

and nothing happens... same for update and promote.

no new version created or promoted

**Comment by golgotow** [comment]
Hello,

this appear after upgrade satellite from 6.4. to 6.5.2


/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- apipie-bindings (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/scripts/katello-cvmanager/cvmanager:20:in `<main>'

**Comment by mara87** [comment]
Hi,
I have same problem as above after upgrade from 6.4 to 6.5.2. Will be there a new release of cvmanager or a fix that work with Sat 6.5 ?

**Comment by evgeni** [comment]
please execute cvmanager with a ruby that has the apipie-bindings gem, e.g. `/usr/bin/tfm-ruby` on a Satellite install

**Comment by brightdroid** [comment]
This works for me, thanks. Though why is there a special ruby version and the gem not installed for the system default ruby?

**Comment by evgeni** [comment]
System ruby on el7 is 2.0, but the foreman/satellite stack needs 2.5, so the ruby25 scl is used. tfm-ruby is just a shortcut.
