### ISSUE TITLE
CVs need one version published

### ISSUE THREAD

**Issue by pcfe** [RedHatSatellite/katello-cvmanager#9]
if a CV is asked to be updated, but no version of it has yet been published, there's a traceback.

It would be nice if either of these happened instead
- katello-cvmanager handled this case and just creates version 1.0
- there was an explicit error message along the lines of "no version yet, please publish one"

Shout if you want a paste of the traceback and I'll post it from my test Sat (ran into it on a customer machine today, but can't really paste from there)

**Comment by evgeni** [comment]
*shout*

**Comment by pcfe** [comment]
Created a 7.3 CV called _cv-os-rhel-7.3_ which uses these yum repos

- sat tools 6.2
- 7server rpms 7.3
- rh common 7.3
- kickstart 7.3

in the Sat webUI, but did not publish any version of it.

Then I edited my _cvmanager.yaml_ to have _cv-os-rhel-7.3_ included under _:publish:_
and I got
```
# ./automated-CCV-script.sh
Tue Nov  8 11:10:05 CET 2016
step: publish
Inspecting cv-os-rhel-7Server
 repo Red_Hat_Enterprise_Linux_7_Server_Kickstart_x86_64_7_2 (id: 80) 
seems newer than CV cv-os-rhel-7Server (id: 3) (2016-11-08 01:54:18 UTC > 
2016-11-07 20:01:51 UTC), lets publish
 repo Red_Hat_Satellite_Tools_6_2_for_RHEL_7_Server_RPMs_x86_64 (id: 1521) 
seems newer than CV cv-os-rhel-7Server (id: 3) (2016-11-08 02:29:08 UTC > 
2016-11-07 20:01:51 UTC), lets publish
 repo Red_Hat_Enterprise_Linux_7_Server_Kickstart_x86_64_7_1 (id: 6) seems 
newer than CV cv-os-rhel-7Server (id: 3) (2016-11-08 02:22:21 UTC > 
2016-11-07 20:01:51 UTC), lets publish
 repo Red_Hat_Enterprise_Linux_7_Server_RPMs_x86_64_7Server (id: 3) seems 
newer than CV cv-os-rhel-7Server (id: 3) (2016-11-08 02:34:48 UTC > 
2016-11-07 20:01:51 UTC), lets publish
 repo Red_Hat_Enterprise_Linux_7_Server_-_RH_Common_RPMs_x86_64_7Server 
(id: 75) seems newer than CV cv-os-rhel-7Server (id: 3) (2016-11-08 
02:29:02 UTC > 2016-11-07 20:01:51 UTC), lets publish
Inspecting cv-os-rhel-7.3
/usr/share/ruby/time.rb:325:in `_parse': no implicit conversion of nil 
into String (TypeError)
        from /usr/share/ruby/time.rb:325:in `parse'
        from ./cvmanager:294:in `rescue in block in publish'
        from ./cvmanager:294:in `block in publish'
        from ./cvmanager:288:in `each'
        from ./cvmanager:288:in `publish'
        from ./cvmanager:349:in `<main>'
```

going back to the webUI and publishing an initial version made cvmanager work as expected again.

**Comment by pcfe** [comment]
commit 03694e8 fixes this for me.
```
# git status
# On branch master
[...]
# ./cvmanager --wait publish
Inspecting cv-test-cvmanager-issue9
/usr/share/ruby/time.rb:325:in `_parse': no implicit conversion of nil 
into String (TypeError)
        from /usr/share/ruby/time.rb:325:in `parse'
        from ./cvmanager:294:in `rescue in block in publish'
        from ./cvmanager:294:in `block in publish'
        from ./cvmanager:288:in `each'
        from ./cvmanager:288:in `publish'
        from ./cvmanager:349:in `<main>'
# git checkout issue-9
Switched to branch 'issue-9'
# ./cvmanager --wait publish
Inspecting cv-test-cvmanager-issue9
 repo Red_Hat_Satellite_Tools_6_2_for_RHEL_7_Server_RPMs_x86_64 (id: 1521) seems newer than CV cv-test-cvmanager-issue9 (id: 30) (2016-11-08 02:29:08 UTC > 0000-01-01 00:00:00 +0024), lets publish
 repo Red_Hat_Enterprise_Linux_7_Server_-_RH_Common_RPMs_x86_64_7_3 (id: 1919) seems newer than CV cv-test-cvmanager-issue9 (id: 30) (2016-11-08 00:10:38 UTC > 0000-01-01 00:00:00 +0024), lets publish
 repo Red_Hat_Enterprise_Linux_7_Server_Kickstart_x86_64_7_3 (id: 1916) seems newer than CV cv-test-cvmanager-issue9 (id: 30) (2016-11-08 02:14:49 UTC > 0000-01-01 00:00:00 +0024), lets publish
 repo Red_Hat_Enterprise_Linux_7_Server_RPMs_x86_64_7_3 (id: 1917) seems newer than CV cv-test-cvmanager-issue9 (id: 30) (2016-11-08 01:58:52 UTC > 0000-01-01 00:00:00 +0024), lets publish
Inspecting cv-os-rhel-7Server
Inspecting cv-os-rhel-7.3
Inspecting cv-os-rhel-7.2
Inspecting cv-os-rhel-7.1
Inspecting cv-os-rhel-6Server
Inspecting cv-os-rhel-6.7
waiting 10 for pending tasks: ["01372c4e-31c8-4b84-99c5-479bddae149f"]
[...]
```
